### ISSUE TITLE
How did you do this

### ISSUE THREAD

**Issue by GiuseppeDiPalma** [jetbridge/paramiko-lambda-layer#16]
**This is not a real issue.**

I tried several times to import paramiko as a layer, but it always gave an error, could I know how you created this layer? 
I am interested in a little tutorial.

**Comment by revmischa** [comment]
It is built in docker - https://github.com/jetbridge/paramiko-lambda-layer/blob/master/Dockerfile
The layer is a zip file of the layer's contents - https://github.com/jetbridge/paramiko-lambda-layer/blob/master/build.sh
that's it!
