### ISSUE TITLE
eu-west-3 region support

### ISSUE THREAD

**Issue by M-Puig** [jetbridge/paramiko-lambda-layer#5]
Hi,
If Possible, I'll really enjoy having an arn for paramiko for the eu-west-3 region.

Thanks a lot !

**Comment by revmischa** [comment]
Python 3.7?

**Comment by M-Puig** [comment]
my function is on 3.8 but it will probably do with 3.7

**Comment by revmischa** [comment]
Try `arn:aws:lambda:eu-west-3:898466741470:layer:paramiko-py37:1`

**Comment by M-Puig** [comment]
Thanks for your fast answers !
However it seems that a dependency is missing; I have the following error when trying to import paramiko : 

Unable to import module 'lambda_function': No module named '_cffi_backend'

**Comment by revmischa** [comment]
The package contains `_cffi_backend.cpython-37m-x86_64-linux-gnu.so` so it's probably a python version issue. Feel free to send a PR to add 3.8
